"""Creacion Vehiculo

Revision ID: 287e63495d8f
Revises: 924915ab7231
Create Date: 2024-06-25 20:03:56.981995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287e63495d8f'
down_revision = '924915ab7231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=30), nullable=False),
    sa.Column('cilindrada', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculo')
    # ### end Alembic commands ###
