"""Creacion Modelo.

Revision ID: 924915ab7231
Revises: 3d21d0847427
Create Date: 2024-06-25 19:55:15.515182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924915ab7231'
down_revision = '3d21d0847427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelo')
    # ### end Alembic commands ###
